---

- name: Reload systemd
  command: systemctl daemon-reload
  become: true

- name: Enable dockerd service
  command: systemctl enable dockerd
  become: true

- name: Enable kubelet service
  command: systemctl enable kubelet
  become: true

- name: Enable kube-proxy service
  command: systemctl enable kube-proxy
  become: true

- name: Restart dockerd service
  service:
    name: dockerd
    state: restarted
    enabled: yes
  become: true

- name: Restart kubelet service
  service:
    name: kubelet
    state: restarted
    enabled: yes
  become: true

- name: Restart kube-proxy service
  service:
    name: kube-proxy
    state: restarted
    enabled: yes
  become: true
