---

kube_apiserver_checksum: "sha1:9acf81d064c4f6e61c3aec2635a827557d3ef522"
kube_apiserver_download_url: "{{ kubebins_download_path}}/kube-apiserver"
kube_controller_manager_checksum: "sha1:0cd2345872e2ce00106012de9f0f1e40801e1917"
kube_controller_manager_download_url: "{{ kubebins_download_path}}/kube-controller-manager"
kube_scheduler_checksum: "sha1:0815b0cdc2542652f9af7909c7d51f3934b8257d"
kube_scheduler_download_url: "{{ kubebins_download_path}}/kube-scheduler"
